from __future__ import annotations

from app.schemas import AssetKind, CatalogModelSpec, NodeType

PRICING_NOTE = (
    "Starting estimate only; final cost may depend on duration, resolution, "
    "character count, and model parameters."
)

CHEAPEST_MODEL_BY_NODE_TYPE = {
    "text_to_image": "wavespeed-ai/z-image/turbo",
    "image_to_image": "wavespeed-ai/z-image-turbo/image-to-image",
    "reference_to_image": "wavespeed-ai/z-image-turbo/image-to-image",
    "upscale_image": "wavespeed-ai/image-upscaler",
    "remove_background": "wavespeed-ai/image-background-remover",
    "remove_object": "wavespeed-ai/z-image/turbo-inpaint",
    "image_to_video": "wavespeed-ai/wan-2.2/i2v-480p-ultra-fast",
    "start_end_to_video": "wavespeed-ai/wan-2.2/i2v-480p-ultra-fast",
    "text_to_video": "wavespeed-ai/wan-2.2/t2v-480p-ultra-fast",
    "reference_to_video": "alibaba/wan-2.6/reference-to-video-flash",
    "video_extend": "vidu/q2-turbo/extend-video",
    "video_effect": "vidu/template/halloween",
    "text_to_speech": "wavespeed-ai/qwen3-tts/text-to-speech",
    "text_to_audio": "wavespeed-ai/qwen3-tts/text-to-speech",
    "speech_to_text": "wavespeed-ai/openai-whisper",
    "generate_voice": "wavespeed-ai/qwen3-tts/voice-design",
    "talking_avatar": "wavespeed-ai/infinitetalk",
    "lip_sync": "wavespeed-ai/latentsync",
    "portrait_transfer": "wavespeed-ai/image-body-swap",
    "image_to_3d": "wavespeed-ai/hunyuan3d-v2-multi-view",
    "text_to_3d": "wavespeed-ai/hunyuan-3d-v3.1/text-to-3d-rapid",
}


def _docs_url(model_id: str | None) -> str | None:
    if not model_id:
        return None
    return f"https://wavespeed.ai/models/{model_id}"


def _entry(
    node_type: NodeType,
    category: str,
    display_name: str,
    description: str,
    output_kind: AssetKind,
    estimated_base_cost_usd: float | None,
    cost_unit: str | None,
    verification_status: str,
    enabled: bool,
    enabled_reason: str,
    default_model_id: str | None = None,
) -> CatalogModelSpec:
    return CatalogModelSpec(
        node_type=node_type.value,
        category=category,
        default_model_id=default_model_id,
        display_name=display_name,
        description=description,
        output_kind=output_kind.value,
        estimated_base_cost_usd=estimated_base_cost_usd,
        cost_unit=cost_unit,
        pricing_note=PRICING_NOTE if estimated_base_cost_usd is not None else None,
        docs_url=_docs_url(default_model_id),
        verification_status=verification_status,
        enabled=enabled,
        enabled_reason=enabled_reason,
    )


MODEL_CATALOG: list[CatalogModelSpec] = [
    _entry(
        node_type=NodeType.upload_image,
        category="input",
        display_name="Upload Image",
        description="Add a local image asset to the project.",
        output_kind=AssetKind.image,
        estimated_base_cost_usd=0.0,
        cost_unit="asset",
        verification_status="verified",
        enabled=True,
        enabled_reason="Local project asset upload; no WaveSpeed model required.",
    ),
    _entry(
        node_type=NodeType.text_to_image,
        category="image",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["text_to_image"],
        display_name="Text to Image",
        description="Generate an image from a text prompt.",
        output_kind=AssetKind.image,
        estimated_base_cost_usd=0.005,
        cost_unit="run",
        verification_status="verified",
        enabled=True,
        enabled_reason="Already implemented and verified in the MVP runner.",
    ),
    _entry(
        node_type=NodeType.image_to_image,
        category="image",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["image_to_image"],
        display_name="Image to Image / Remix",
        description="Remix or transform a source image with a prompt.",
        output_kind=AssetKind.image,
        estimated_base_cost_usd=0.005,
        cost_unit="run",
        verification_status="verified",
        enabled=True,
        enabled_reason="Already implemented and verified in the MVP runner.",
    ),
    _entry(
        node_type=NodeType.reference_to_image,
        category="image",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["reference_to_image"],
        display_name="Reference to Image",
        description="Use a reference image to guide image generation.",
        output_kind=AssetKind.image,
        estimated_base_cost_usd=0.005,
        cost_unit="run",
        verification_status="candidate",
        enabled=False,
        enabled_reason="Disabled until the reference-image product UX is clarified.",
    ),
    _entry(
        node_type=NodeType.upscale_image,
        category="image",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["upscale_image"],
        display_name="Upscale Image",
        description="Increase image resolution.",
        output_kind=AssetKind.image,
        estimated_base_cost_usd=0.01,
        cost_unit="run",
        verification_status="verified",
        enabled=True,
        enabled_reason="Official request fields verified for image, target_resolution, and output_format.",
    ),
    _entry(
        node_type=NodeType.remove_background,
        category="image",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["remove_background"],
        display_name="Remove Background",
        description="Remove the background from an image.",
        output_kind=AssetKind.image,
        estimated_base_cost_usd=0.004,
        cost_unit="run",
        verification_status="verified",
        enabled=True,
        enabled_reason="Official request field verified for image input.",
    ),
    _entry(
        node_type=NodeType.remove_object,
        category="image",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["remove_object"],
        display_name="Remove Object",
        description="Remove selected objects from an image.",
        output_kind=AssetKind.image,
        estimated_base_cost_usd=0.02,
        cost_unit="run",
        verification_status="disabled",
        enabled=False,
        enabled_reason="Disabled because object removal requires mask/inpaint UX and verified fields.",
    ),
    _entry(
        node_type=NodeType.image_to_video,
        category="video",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["image_to_video"],
        display_name="Image to Video",
        description="Animate an image into a short video.",
        output_kind=AssetKind.video,
        estimated_base_cost_usd=0.05,
        cost_unit="run",
        verification_status="verified",
        enabled=True,
        enabled_reason="Official request fields verified for image, prompt, duration, seed, and optional last_image.",
    ),
    _entry(
        node_type=NodeType.start_end_to_video,
        category="video",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["start_end_to_video"],
        display_name="Start-End Video",
        description="Create video motion between starting and ending images.",
        output_kind=AssetKind.video,
        estimated_base_cost_usd=0.05,
        cost_unit="run",
        verification_status="needs_params",
        enabled=False,
        enabled_reason="Disabled until last-image support and request fields are verified.",
    ),
    _entry(
        node_type=NodeType.text_to_video,
        category="video",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["text_to_video"],
        display_name="Text to Video",
        description="Generate a short video from a text prompt.",
        output_kind=AssetKind.video,
        estimated_base_cost_usd=0.05,
        cost_unit="run",
        verification_status="disabled",
        enabled=False,
        enabled_reason="Disabled for now; request fields have not been verified.",
    ),
    _entry(
        node_type=NodeType.reference_to_video,
        category="video",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["reference_to_video"],
        display_name="Reference to Video",
        description="Use reference media to guide video generation.",
        output_kind=AssetKind.video,
        estimated_base_cost_usd=0.13,
        cost_unit="run",
        verification_status="disabled",
        enabled=False,
        enabled_reason="Disabled for now; request fields have not been verified.",
    ),
    _entry(
        node_type=NodeType.video_extend,
        category="video",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["video_extend"],
        display_name="Video Extend",
        description="Extend an existing video clip.",
        output_kind=AssetKind.video,
        estimated_base_cost_usd=0.2,
        cost_unit="run",
        verification_status="disabled",
        enabled=False,
        enabled_reason="Disabled for now; request fields have not been verified.",
    ),
    _entry(
        node_type=NodeType.video_effect,
        category="video",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["video_effect"],
        display_name="Video Effect",
        description="Apply a model-specific video effect.",
        output_kind=AssetKind.video,
        estimated_base_cost_usd=0.05,
        cost_unit="run",
        verification_status="disabled",
        enabled=False,
        enabled_reason="Disabled for now; request fields have not been verified.",
    ),
    _entry(
        node_type=NodeType.text_to_speech,
        category="audio",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["text_to_speech"],
        display_name="Text to Speech",
        description="Generate speech audio from text.",
        output_kind=AssetKind.audio,
        estimated_base_cost_usd=0.005,
        cost_unit="run",
        verification_status="verified",
        enabled=True,
        enabled_reason="Official request fields verified for text, language, voice, and style_instruction.",
    ),
    _entry(
        node_type=NodeType.text_to_audio,
        category="audio",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["text_to_audio"],
        display_name="Text to Audio",
        description="Generate audio from text.",
        output_kind=AssetKind.audio,
        estimated_base_cost_usd=0.005,
        cost_unit="run",
        verification_status="candidate",
        enabled=False,
        enabled_reason="Disabled until product language and request fields are verified.",
    ),
    _entry(
        node_type=NodeType.speech_to_text,
        category="audio",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["speech_to_text"],
        display_name="Speech to Text",
        description="Transcribe speech audio into text.",
        output_kind=AssetKind.other,
        estimated_base_cost_usd=0.001,
        cost_unit="run",
        verification_status="disabled",
        enabled=False,
        enabled_reason="Disabled for now; request fields have not been verified.",
    ),
    _entry(
        node_type=NodeType.generate_voice,
        category="audio",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["generate_voice"],
        display_name="Generate Voice",
        description="Design or generate a voice.",
        output_kind=AssetKind.audio,
        estimated_base_cost_usd=0.005,
        cost_unit="run",
        verification_status="disabled",
        enabled=False,
        enabled_reason="Disabled for now; request fields have not been verified.",
    ),
    _entry(
        node_type=NodeType.talking_avatar,
        category="avatar",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["talking_avatar"],
        display_name="Talking Avatar",
        description="Create a talking avatar video.",
        output_kind=AssetKind.video,
        estimated_base_cost_usd=0.15,
        cost_unit="run",
        verification_status="disabled",
        enabled=False,
        enabled_reason="Disabled for now; request fields have not been verified.",
    ),
    _entry(
        node_type=NodeType.lip_sync,
        category="avatar",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["lip_sync"],
        display_name="Lip Sync",
        description="Synchronize a portrait or video with speech audio.",
        output_kind=AssetKind.video,
        estimated_base_cost_usd=0.05,
        cost_unit="run",
        verification_status="disabled",
        enabled=False,
        enabled_reason="Disabled for now; request fields have not been verified.",
    ),
    _entry(
        node_type=NodeType.portrait_transfer,
        category="avatar",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["portrait_transfer"],
        display_name="Portrait Transfer",
        description="Transfer or swap portrait appearance across media.",
        output_kind=AssetKind.video,
        estimated_base_cost_usd=0.05,
        cost_unit="run",
        verification_status="disabled",
        enabled=False,
        enabled_reason="Disabled for now; request fields have not been verified.",
    ),
    _entry(
        node_type=NodeType.image_to_3d,
        category="3d",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["image_to_3d"],
        display_name="Image to 3D",
        description="Generate a 3D asset from one or more images.",
        output_kind=AssetKind.other,
        estimated_base_cost_usd=0.01,
        cost_unit="run",
        verification_status="disabled",
        enabled=False,
        enabled_reason="Disabled for now; multi-view inputs and request fields have not been verified.",
    ),
    _entry(
        node_type=NodeType.text_to_3d,
        category="3d",
        default_model_id=CHEAPEST_MODEL_BY_NODE_TYPE["text_to_3d"],
        display_name="Text to 3D",
        description="Generate a 3D asset from text.",
        output_kind=AssetKind.other,
        estimated_base_cost_usd=0.022,
        cost_unit="run",
        verification_status="disabled",
        enabled=False,
        enabled_reason="Disabled for now; request fields have not been verified.",
    ),
    _entry(
        node_type=NodeType.generic_wavespeed,
        category="system",
        display_name="Generic WaveSpeed",
        description="Fallback router concept for future model execution.",
        output_kind=AssetKind.other,
        estimated_base_cost_usd=None,
        cost_unit=None,
        verification_status="experimental",
        enabled=False,
        enabled_reason="Not exposed as a runnable model.",
    ),
]

CATALOG_BY_NODE_TYPE = {entry.node_type: entry for entry in MODEL_CATALOG}


def get_catalog_entry(node_type: str) -> CatalogModelSpec | None:
    return CATALOG_BY_NODE_TYPE.get(node_type)


def list_catalog_entries() -> list[CatalogModelSpec]:
    return list(MODEL_CATALOG)
